# Generated by Django 4.0.6 on 2022-07-16 12:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('experience', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=50)),
                ('expertise', models.CharField(max_length=100)),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
            ],
        ),
    ]
